"""Calibration report: ties analysis.io + analysis.scales + analysis.forward_model
together into one reproducible set of recommended simulator defaults.

Run as a script:
    .venv/bin/python3 -m analysis.report

Prints a human-readable report and writes analysis/calibration_report.md.
Every recommended value states the real-data quantity it was derived from,
so re-running this after the datasets change keeps the C++ defaults in sync.
"""
from __future__ import annotations

from pathlib import Path

from . import io, scales, forward_model

REPORT_PATH = Path(__file__).resolve().parent / "calibration_report.md"

# Assumed daytime convective boundary-layer depth. Not derivable from these
# datasets (no vertical profile data); 500-1500 m is the typical range for a
# daytime mixed layer over land, and 800 m is a mid-range value.
ASSUMED_MIXING_HEIGHT_M = 800.0

# Typical PM2.5 dry-deposition velocity (~0.1 cm/s). Spread over the mixing
# height this gives a first-order removal rate of ~1.25e-6 /s (~9 day e-folding).
DEPOSITION_VELOCITY_M_S = 1.0e-3

# Sensor noise std as a fraction of the default plume's peak model
# concentration; matches SourceEstimationConfig::relative_model_error.
RELATIVE_SENSOR_NOISE = 0.05


def build_report() -> dict:
    wildfire = io.load_wildfire()
    multimonth = io.load_multimonth()

    spacing = scales.site_spacing_stats(wildfire)
    conc_wildfire = scales.concentration_stats(wildfire)
    conc_multimonth = scales.concentration_stats(multimonth)
    sample_interval_s = scales.sampling_interval_s(wildfire)
    event = scales.event_timescales(wildfire)
    decorr_s = scales.autocorrelation_time_s(wildfire)
    wind = scales.wind_stats(multimonth)  # wildfire set has sparser wind coverage

    # --- Translate into simulator defaults --------------------------------
    domain_span_m = 5000.0  # current Config.hpp DomainConfig extent (x_max-x_min)

    # The domain is a scale model of the network: lengths shrink by
    # `projection_scale`, and exported time is stretched by its inverse so
    # wind speeds (m/s) are the same in the domain and in real geography.
    # Real-world durations therefore map to simulation seconds / time_stretch,
    # and real rates to simulation rates * time_stretch.
    projection_scale = scales.domain_projection_scale(wildfire, domain_span_m=domain_span_m)
    time_stretch = 1.0 / projection_scale
    deposition_rate_sim = DEPOSITION_VELOCITY_M_S / ASSUMED_MIXING_HEIGHT_M * time_stretch

    representative_wind_u = wind["speed_median_m_s"]
    plume = forward_model.simulate_default_plume(
        wind_u=representative_wind_u, wind_v=0.0, deposition_rate=deposition_rate_sim)
    conc_scale = forward_model.solve_conc_scale(
        raw_peak_model_conc=plume["quasi_steady_peak"],
        target_peak_ugm3=event["peak_ugm3"],
        mixing_height_m=ASSUMED_MIXING_HEIGHT_M,
    )

    sigma_fraction_of_extent = spacing["nearest_neighbor_median_m"] / spacing["network_extent_m"]
    recommended_source_sigma = max(20.0, sigma_fraction_of_extent * domain_span_m)

    recommendations = {
        "mixing_height_m": ASSUMED_MIXING_HEIGHT_M,
        "conc_scale_ug_per_m2": conc_scale,
        "sensor_noise_std_model_units": RELATIVE_SENSOR_NOISE * plume["quasi_steady_peak"],
        "source_sigma_m": recommended_source_sigma,
        "deposition_rate_per_sim_s": deposition_rate_sim,
        "representative_wind_speed_m_s": representative_wind_u,
        "wind_speed_p90_m_s": wind["speed_p90_m_s"],
        "export_time_stretch": time_stretch,
        "faithful_source_decay_rate_per_sim_s": (time_stretch / event["decay_tau_s"]) if event["decay_tau_s"] else None,
        "faithful_source_lifespan_sim_s": event["event_duration_s"] / time_stretch,
        "hourly_report_period_sim_s": sample_interval_s / time_stretch,
        "decorrelation_time_s": decorr_s,
    }

    return {
        "spacing": spacing,
        "conc_wildfire": conc_wildfire,
        "conc_multimonth": conc_multimonth,
        "sample_interval_s": sample_interval_s,
        "event": event,
        "decorrelation_time_s": decorr_s,
        "wind": wind,
        "forward_model_plume": {k: v for k, v in plume.items() if k != "peak_history"},
        "recommendations": recommendations,
    }


def format_report(result: dict) -> str:
    r = result["recommendations"]
    lines = []
    lines.append("# Calibration report\n")
    lines.append(
        "Generated by `analysis/report.py` from `wildfire_pm25_dataset.csv` "
        "(Nov 2024 NY-metro wildfire event, 38 sites) and "
        "`multimonth_pm25_dataset.csv` (Sep 2023-Mar 2024, 29 sites).\n"
    )

    lines.append("## Site network geometry (wildfire dataset)")
    for k, v in result["spacing"].items():
        lines.append(f"- {k}: {v:.1f}" if isinstance(v, float) else f"- {k}: {v}")

    lines.append("\n## Concentration scale (ug/m^3)")
    lines.append("wildfire event:")
    for k, v in result["conc_wildfire"].items():
        lines.append(f"  - {k}: {v:.2f}")
    lines.append("multimonth baseline:")
    for k, v in result["conc_multimonth"].items():
        lines.append(f"  - {k}: {v:.2f}")

    lines.append("\n## Temporal scales")
    lines.append(f"- hourly sample interval (s): {result['sample_interval_s']:.0f}")
    lines.append(f"- decorrelation time (s): {result['decorrelation_time_s']:.0f}")
    e = result["event"]
    lines.append(f"- event peak: {e['peak_ugm3']:.1f} ug/m^3 at {e['peak_time_utc']}")
    lines.append(f"- rise tau (s): {e['rise_tau_s']}")
    lines.append(f"- decay tau (s): {e['decay_tau_s']}")
    lines.append(f"- event duration above 20% threshold (s): {e['event_duration_s']:.0f}")

    lines.append("\n## Wind (from multimonth dataset)")
    for k, v in result["wind"].items():
        lines.append(f"- {k}: {v:.2f}")

    lines.append("\n## Forward-model replica (default Config.hpp params)")
    for k, v in result["forward_model_plume"].items():
        lines.append(f"- {k}: {v:.6g}")

    lines.append("\n## Recommended simulator defaults")
    for k, v in r.items():
        lines.append(f"- {k}: {v}")

    return "\n".join(lines) + "\n"


def main() -> None:
    result = build_report()
    text = format_report(result)
    print(text)
    REPORT_PATH.write_text(text)
    print(f"\nWrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
